# Generated by Django 4.2 on 2023-04-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('right', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150, unique=True)),
                ('rights', models.ManyToManyField(to='right.rights')),
            ],
        ),
    ]
