# Generated by Django 4.2 on 2023-04-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rights',
            field=models.ManyToManyField(blank=True, to='right.rights'),
        ),
    ]
